### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by egoist** [babel-utils/babel-plugin-tester#15]
since you're using [async function](https://github.com/babel-utils/babel-plugin-tester/blob/master/src/index.js#L95) here and didn't use babel-plugin-transform-runtime.

Maybe set the target of  `env` preset to `6` or add `transform-regenerator` to blacklist?

**Comment by kentcdodds** [comment]
I'd love to only support node 8, but I don't think that's reasonable at this point, so yeah, let's fixup things so this code works in node 6. Could you submit a PR to do that? I don't really care so much how it's done (so long as no changes are made to the source code).
