### ISSUE TITLE
Maybe format should also be executed on output file

### ISSUE THREAD

**Issue by NoDocCat** [babel-utils/babel-plugin-tester#156]
- `babel-plugin-tester` version: 11.0.4
- `node` version: 19.5.0
- `npm` (or `yarn`) version: pnpm 7.26.0

Relevant code or config

```javascript
pluginTester({
  plugin: babelPluginJsxAssetUrlImport,
  fixtures: path.join(__dirname, 'fixtures'),
  babelOptions: {
    plugins: ['@babel/plugin-syntax-jsx']
  }
});
```

Problem description:

I create a simple fixture, then tormented by semicolons and blank lines. like this:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/20502666/215804367-17689748-5911-4d42-bbf9-2ad23af134a0.png">

In fact the two files are exactly the same

Suggested solution:

before run expect, maybe should format `output file` use prettier.

**Comment by NoDocCat** [comment]
Sorry to disturb you, I found the snapshot from #51, Very convenient.

**Comment by Schommer79** [comment]
I would also support this becoming a feature. Unlike @suiyun39, I am using Jasmine, so snapshot is not an option for me. Further, I don't feel it should be the responsibility of the developer to predict how babel will format the results. Nor should the developer need to write an output that is less readable in order to match formatting.

Alternately, and this would actually be my preference, you could support comparing ast's directly. Format would then become irrelevant.

**Comment by Xunnamius** [comment]
I'd accept a PR for an ast-based comparison mode. That sounds like a good idea to explore. 

As for formatting output files, I rely on my IDE for that (which calls out to Babel and Prettier). I'm wary of BPT mutating files behind the scenes any more than it already is. And it seems prudent to keep the `fixtures` and `tests` APIs as close as possible; would we also format the user's output strings for `tests` objects? And how would this interact with `formatResult` and `outputFixture`?

Currently, BPT provides snapshot-like. functionality without needing Jest: it will generate your `output.js` file for you if it doesn't already exist, and will recreate it if it's deleted.

**Comment by Schommer79** [comment]
@Xunnamius I'll try to put something together when I get some time. Setting aside the api for using it, I am hopeful that it will just be a matter of calling the babel parser on both the result and the output and stripping out location information. The deep comparison tools of expect toEqual should be able to handle the rest.

I haven't done much with TypeScript before, so it may take a bit longer than I would like.
