### ISSUE TITLE
Cannot load babel plugins before SUT using .babelrc in fixtures

### ISSUE THREAD

**Issue by real34** [babel-utils/babel-plugin-tester#18]
I am struggling to test a case where another plugin is changing the `resolveModuleSource` babel option. It seems that on options merge, plugins from a fixture `.babelrc` file are appended _after_ the tested plugin. See below.

- `babel-plugin-tester` version: 3.3.0
- `node` version: 8.2
- `npm` (or `yarn`) version: yarn 0.27.5

Relevant code or config (`.babelrc` from fixtures)

```json
{
  "plugins": [["./custom_resolver.js", { "foo": "bar" }]]
}
```

What you did:

I created a test with the following option: `babelOptions: { babelrc: true },`

What happened:

The custom babel config was loaded, but plugins were added after the SUT, whereas I needed them to be loaded before the SUT.

Reproduction repository:

See https://github.com/real34/tmp-babel-plugin-inline-import-graphql-ast/commit/29ee949fb817615bd61553d01e55af11baf2d19f

You can checkout the sample repo and run `yarn test` to reproduce the error. It should generate a snapshot file without any error (the error is due to plugins sort order, which causes https://github.com/real34/tmp-babel-plugin-inline-import-graphql-ast/blob/29ee949fb817615bd61553d01e55af11baf2d19f/index.js#L20 to not be executed with the correct module resolver)

Suggested solution:

It would be great to provide/document a way to create a `.babelrc` file where the plugin and its options could be inserted anywhere in the plugins definitions. Or at least how to configure plugins to be run before the SUT.

The simplest solution I can think of would be to prepend plugins definition in https://github.com/babel-utils/babel-plugin-tester/blob/6085c16ff6d15c2651b0ade26d536e42838d337f/src/index.js#L213 from a new option key (something like: `babelPreviousPlugins` for instance)... but it feels a bit hacky no?

Another solution for my use case would be to support `.babelrc.js` files (see https://github.com/babel/babel/issues/4630), which may allow here to define a custom source resolver

**Comment by kentcdodds** [comment]
Hey @real34! :wave:

Thanks for the issue. I'm interested in what you say here:

> Another solution for my use case would be to support .babelrc.js files (see babel/babel#4630), which may allow here to define a custom source resolver

I don't want to add logic to support that, but did you know you can [make `.babelrc.js` work today](https://github.com/babel/babel/pull/4892#issuecomment-304537510)? Would that work for you?
