### ISSUE TITLE
The line feed on windows is failing the tests

### ISSUE THREAD

**Issue by ncochard** [babel-utils/babel-plugin-tester#22]
Hello

I'm using `babel-plugin-tester` to test a Babel plugin I am working on. (Great tool BTW; thanks for sharing this.)

My tests were failing for no apparent reason. Then I realize that the following line of code was returning an error because of a difference with the line feed `\r\n` vs `\n`.

I fixed the problem by replacing the following line of code:

    assert.equal(actual, output, 'actual output does not match output.js')
    
... with this ...

    const normalizeNewline = require('normalize-newline');
    assert.equal(normalizeNewline(actual), normalizeNewline(output), 'actual output does not match output.js')

**Comment by kentcdodds** [comment]
Hi @ncochard!

That makes sense. Normally in my projects I'll include a `.gitattributes` that includes this:

```
*.js text eol=lf
```

This helps me avoid these kinds of problems. That said, I can understand why this tool should be built to work regardless. So feel free to [open a pull request](http://makeapullrequest.com) to address this. Thanks!

**Comment by eps1lon** [comment]
> Normally in my projects I'll include a .gitattributes that includes this:

I think this should be the accepted solution. The linefeed is currently [hardcoded into babel](https://github.com/babel/babel/blob/8f26f6df8355540dd8f351e9f71f7bf056838e2c/packages/babel-generator/src/printer.js#L226) so any test that expectes `\r\n` as a linefeed should actually fail. The [babel repo itself uses `text eol=lf`](https://github.com/babel/babel/blob/8f26f6df8355540dd8f351e9f71f7bf056838e2c/packages/babel-generator/src/printer.js#L226) so I don't think this is the right place for a fix. If anything then `@babel/generator` should be fixed.
