### ISSUE TITLE
Support babel 7.

### ISSUE THREAD

**Issue by cameron-martin** [babel-utils/babel-plugin-tester#23]
- `babel-plugin-tester` version: v5.0.0
- `node` version: N/a
- `npm` (or `yarn`) version: N/a

**What you did:**
Tried to parse typescript using babel 7.

**What happened:**
It would not parse typescript.

**Problem description:**
Basically this npm package imports `babel-core`, but it was renamed to `@babel/core` in babel 7.

Suggested solution:
Possibly create a branch for babel 7 that imports `@babel/core` instead of `babel-core` and publish an alpha/beta of a new major version on the `next` npm channel from this branch.

**Comment by kentcdodds** [comment]
Yeah, I like your solution. Seems like something I'll have to do myself. I'll try to get to it asap.

**Comment by cameron-martin** [comment]
If you create a babel7 branch then I'd be happy to send a PR to it.

**Comment by cameron-martin** [comment]
Actually it may be possible to use [`babel-bridge`](https://github.com/babel/babel-bridge) for this. I'll try it out and report back :)

**Comment by kentcdodds** [comment]
I like that solution.

When babel 7 is officially released then we'll only support that version going forward.

**Comment by cameron-martin** [comment]
I can confirm this works, closing.

**Comment by cameron-martin** [comment]
I don't remember exactly what setup I had, but by my previous comment it involved [`babel-bridge`](https://github.com/babel/babel-bridge).

What issues are you having?

**Comment by jorgeobsidian** [comment]
when I run it I'm getting

```
 Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure youhave a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```

**Comment by kentcdodds** [comment]
Try `npm install --save-dev babel-core@7.0.0-bridge.0`

**Comment by jorgeobsidian** [comment]
Amazing, thanks for the quick response! All good now

**Comment by kentcdodds** [comment]
Yeah, let's get this thing all updated to the latest of everything and push a major version bump :+1:

**Comment by kontrollanten** [comment]
I get problem when using babel 7, it seems that I can't spy on `babel.transform`. Below is the error.

I've created a branch, `pr/babel-7`, if someone would have time to dig further into this. It looks related to https://github.com/facebook/jest/issues/7118 

> TypeError: Cannot set property transform of #<Object> which has only a getter.

**Comment by malbernaz** [comment]
+1 for that!

**Comment by kentcdodds** [comment]
I'm pretty sure this has been resolved...

**Comment by kentcdodds** [comment]
I'm pretty sure this has been resolved...

**Comment by cameron-martin** [comment]
This was reopened to update the dependencies to Babel 7, which appears to not be done yet.

**Comment by kentcdodds** [comment]
Oh, whoops, I thought that had already been done. Would you like to do that?

**Comment by malbernaz** [comment]
I can pick this. Is it just a matter of updating to `@babel/core`? It would be a breaking change, right?

**Comment by kentcdodds** [comment]
I'm guessing so

**Comment by kontrollanten** [comment]
@malbernaz I've created a branch where I started with this work, https://github.com/babel-utils/babel-plugin-tester/tree/pr/babel-7 I had problems with the tests though. I guess it's possible to solve if you've got one hour or so.

**Comment by malbernaz** [comment]
Hey @kontrollanten I gave this a shot yesterday and had a problem mocking `babel.transform`. From what I can see you already solved the problem I had.

```js
transformSpy = jest.spyOn(babel, 'transform', 'get')
```

I'll try again soon and make a PR.

Thanks for the directions!

**Comment by kontrollanten** [comment]
I'm not sure I've solved it, I wasn't able to make it working. But I hope it can push you forward, otherwise let me know and we'll solve it together.
