### ISSUE TITLE
ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by maciej-gurban** [babel-utils/babel-plugin-tester#24]
- `babel-plugin-tester` 5.0.0:
- `node` 8.7.0:
- `npm` 5.4.2:

Relevant code or config

```javascript
const pluginTester = require('babel-plugin-tester');

// normally you would import this from your plugin module
function identifierReversePlugin() {
  return {
    name: 'identifier reverse',
    visitor: {
      Identifier(idPath) {
        idPath.node.name = idPath.node.name.split('').reverse().join('')
      },
    },
  }
}

pluginTester({
  plugin: identifierReversePlugin,
  snapshot: true,
  tests: [
    {code: '"hello";', snapshot: false},
    {
      code: 'var hello = "hi";',
      output: 'var olleh = "hi";',
    },
    `
      function sayHi(person) {
        return 'Hello ' + person + '!'
      }
      console.log(sayHi('Jenny'))
    `,
  ],
})
```

What you did:
Run the sample code from the docs

What happened:
Throws with:
```
  return describe(describeBlockTitle, function () {
  ^

ReferenceError: describe is not defined
```

**Comment by kentcdodds** [comment]
What testing framework are you using?

**Comment by maciej-gurban** [comment]
My bad, I didn't read the beggining of the docs. I assumed this lib ships
with its own assertion/test runner. I'll try with Jest.

**Comment by blankzust** [comment]
node @kentcdodds

**Comment by kentcdodds** [comment]
@blankzust, this requires that you run your tests with a framework that supports global `describe` and `it` functions. Frameworks like Jest (recommended), Mocha, or Jasmine.

**Comment by blankzust** [comment]
ok,I will retry it and thx @kentcdodds

**Comment by Li357** [comment]
How do I get this to work? I've installed Jest globally (and locally), and I've read that Babel comes bundled with `babel-jest` which should handle the globals right (though I'm trying to use Babel 7, which may conflict with it). But I still get `describe is not defined`. Is there something I have to import, or configure with Babel/Jest?

**Comment by kentcdodds** [comment]
How are you running it?

**Comment by Li357** [comment]
That's what I'm not clear on. Am I supposed to let Jest search for the tests itself, or am I supposed to directly feed the JavaScript module I execute `pluginTester` into the Node REPL?

I tried:

    node test/index.js
    jest

Running jest plain does not find the tests. I don't have any Jest configuration.

**Comment by kentcdodds** [comment]
I recommend spending a few minutes in the jest documentation 👍
