### ISSUE TITLE
[Request|Idea]: Improve assertion error on fixture

### ISSUE THREAD

**Issue by kwelch** [babel-utils/babel-plugin-tester#36]
- `babel-plugin-tester` version:5.5.2
- `node` version: v8.11.2
- `npm` (or `yarn`) version: yarn@1.7.0

What you did:
I have a fixture setup with an input/output code file and the following test configuration. 

![config](https://user-images.githubusercontent.com/1295580/49233169-0863eb00-f3bb-11e8-8a35-abae6c780b70.png)

What happened:
On error the messaging is very generic and doesn't clue into the failure. 

Screenshot of fixture input/output error:
<img width="599" alt="Screenshot of fixture input/output error" src="https://user-images.githubusercontent.com/1295580/49233577-e6b73380-f3bb-11e8-91fa-11e86f6d3c7a.png">

Screenshot of snapshot error: 
<img width="590" alt="Screenshot of snapshot error" src="https://user-images.githubusercontent.com/1295580/49233585-ed45ab00-f3bb-11e8-9906-a06a2266b165.png">

Reproduction repository:
I don't have one at this point that is public.

Problem description:
Error is not descriptive doesn't help point the user to resolution.

Suggested solution:
I know that snapshots look better since that functionality is built into jest. I think we should be able to use similar logic to find the difference between the 2 files contents.

**Comment by kentcdodds** [comment]
Agreed. Would you like to open a PR 👍

**Comment by kwelch** [comment]
I am hoping to do that, but I wanted to get the idea out here in case someone has free time before me. 😄

**Comment by kwelch** [comment]
*Plot twist*
It appears if you use `fixtures` with `code.js` & `output.js` files the diffing works as expected. 

This is just scoped to cases where you declare a fixture & fixture output.

**Comment by kwelch** [comment]
After debugging this is what I have learned. 

Both [fixtures](https://github.com/babel-utils/babel-plugin-tester/blob/master/src/index.js#L256-L260) and [fixture output](https://github.com/babel-utils/babel-plugin-tester/blob/master/src/index.js#L168) assert in the same way. 

It appears the nice formatting that I am hoping for is coming out of jest for free. :tada:

It appears that fixtures defined within a test are wrapping in a few too many layers for the errors to get thrown properly for this formatting. However in the [associated test](https://github.com/babel-utils/babel-plugin-tester/blob/master/src/__tests__/index.js#L222-L241) for fixture & outputFixture, the assertion error is thrown and can be caught properly with an expected and actual. 

The only difference I am left with is that the tests array is ran as promises. However, if assertion errors in a promise don't format pretty, that sounds like it is not a concern of this package and more a jest error. 

_brain dump end_

**Comment by kentcdodds** [comment]
Thanks for digging! Sounds like we can't do anything about it here so I'll close this issue out. Thanks!
