### ISSUE TITLE
Feature request - Plugin options in fixtures directory

### ISSUE THREAD

**Issue by merceyz** [babel-utils/babel-plugin-tester#40]
When using fixtures it would be nice if it was possible to provide plugin options in a `options.json` file. 
This would make it easier to test different features of a plugin, where different settings can be provided.

**Comment by kentcdodds** [comment]
I'm in favor 👍 Would you be willing to [make a pull request](http://makeapullrequest.com/)?

**Comment by merceyz** [comment]
Yes, just wanted confirmation that it was something that would be welcomed
