### ISSUE TITLE
Using `api.assertVersion()` in plugin breaks this package.

### ISSUE THREAD

**Issue by oliverfindl** [babel-utils/babel-plugin-tester#58]
- `babel-plugin-tester` version: 8.0.0, 8.0.1
- `node` version: 10.18.1
- `npm` (or `yarn`) version: 6.13.6 (`npm`)

---

**Relevant code or config:**

Dummy plugin using `api.assertVersion`.
```javascript
const { declare } = require("@babel/helper-plugin-utils");
const plugin = declare(({ assertVersion }) => {
	assertVersion(7);
	return { name: "dummy-plugin" };
});
```

---

**What you did:**

Execute tests.

---

**What happened:**

Requires Babel "^7.0.0-beta.41", but was loaded with "7.7.2". You'll need to update your @babel/core version.

Attempting to infer the name of your plugin failed. Tried to invoke the plugin which threw the error.

---

**Reproduction repository:**

[babel-plugin-remove-template-literals-whitespace](https://github.com/oliverfindl/babel-plugin-remove-template-literals-whitespace)

---

**Problem description:**

Issue lies in [getPluginName](https://github.com/babel-utils/babel-plugin-tester/blob/60e5c078cd6d60894dd3bc20cb062d09eae562af/src/plugin-tester.js#L438) method, which has exactly same issue as is mentioned [here](https://github.com/babel/babel/issues/10106#issuecomment-507845756). This method instantiate provided plugin with exports of [@babel/core](https://github.com/babel/babel/tree/master/packages/babel-core) obtained in [pluginTester](https://github.com/babel-utils/babel-plugin-tester/blob/60e5c078cd6d60894dd3bc20cb062d09eae562af/src/plugin-tester.js#L38) method.

As a hotfix, `api.assertVersion` method in passed [babel reference](https://github.com/babel-utils/babel-plugin-tester/blob/60e5c078cd6d60894dd3bc20cb062d09eae562af/src/plugin-tester.js#L441) can be overloaded with noop only in [getPluginName](https://github.com/babel-utils/babel-plugin-tester/blob/60e5c078cd6d60894dd3bc20cb062d09eae562af/src/plugin-tester.js#L438) method.
```javascript
name = plugin(/* api = */ Object.assign({}, babel, { assertVersion: noop }), /* options = */ {}, /* dirname = */ "").name;
```
But still, a proper fix will be required.

---

**Suggested solution:**

Not sure.

**Comment by kentcdodds** [comment]
Hi @oliverfindl 👋

The easiest way to solve this problem would be for you to provide a plugin name manually. So change [this](https://github.com/oliverfindl/babel-plugin-remove-template-literals-whitespace/blob/e54a9c3738abafd1a82770764270b23dd5c87e10/test/index.spec.js#L9-L13) to this:

```javascript
pluginTester({
	plugin: require(pluginPath),
	pluginName: "remove-template-literals-whitespace",
	pluginOptions: { verbose: false },
	fixtures: fixturesPath
});
```

I don't think there's much else we can do. The inference is just a convenience. Thanks!

**Comment by oliverfindl** [comment]
Hello @kentcdodds,

this did the trick! Works as expected.

Thank you.
