### ISSUE TITLE
TypeError: pluginTester is not a function (on version 8.0.1)

### ISSUE THREAD

**Issue by RIP21** [babel-utils/babel-plugin-tester#61]
- `babel-plugin-tester` version: 8.0.1
- `node` version: v12.14.1
- `yarn` version: 1.21.1

Relevant code or config

```javascript
const pluginTester = require("babel-plugin-tester");

pluginTester({});
```

What you did:
Ran the `jest`.

What happened:

```
TypeError: pluginTester is not a function
```

Problem description:

```
  "devDependencies": {
    "babel-plugin-tester": "8.0.1",
    "jest": "^25.1.0",
    "prettier": "^1.19.1"
  }
```

and run `jest`
It fails with the error above. (all other non-babel tester tests are green)

If I return back to version 7 it works fine. Have no idea what is wrong TBH :)

If I try to return jest to version 23 and 24 from 25, result is still the same. So probably some wrong babel compilation of source code of version 8? Have no idea TBH.

Suggested solution:

¯\\_(ツ)\_/¯

**Comment by ben-rogerson** [comment]
I'm receiving the same error, for everyone `npm i babel-plugin-tester@7.0.4` until there's a fix/workaround.

**Comment by charlesbodman** [comment]
The issue is probably a switch to ESModules.

You need to explicitly use ".default" as part of the requirement. 

`const pluginTester = require("babel-plugin-tester").default;`

**Comment by RIP21** [comment]
Kinda breaking, isn't it :D Should be mentioned in docs :)

**Comment by kentcdodds** [comment]
Sorry about that!

**Comment by kentcdodds** [comment]
@all-contributors please add @RIP21 for bugs

**Comment by RIP21** [comment]
@kentcdodds hehe, no problems. I see you already fixed the Readme :) (adding it to releases page as breaking changes section will be awesome too. I always looking for breaking stuff there)
Thanks a lot :) I assume you can close it now :)

**Comment by kentcdodds** [comment]
Adding that now.
