### ISSUE TITLE
same files - no match

### ISSUE THREAD

**Issue by zabakala** [babel-utils/babel-plugin-tester#65]
Hi. I am diving into a simple test. Despite the content match of both the input and output files, the test results do differ in content due to the presence of (invisible) dots as apparent from the img below. How can it be avoided?

![dots](https://user-images.githubusercontent.com/6930312/75113642-eace1180-564f-11ea-8768-13cf1ed20959.PNG)

**Comment by ngquhuanbl** [comment]
@zabakala @TanDung2512 
You can try this workaround which works in my case.
Use `\n` in the line feed positions (which appears to be the reported differences) in the value of the `code` field.
Btw, it's weird that some of my tests (which also includes line feed) doesn't fail like the others.
In the below screenshot, the former test does not fail, but the later does (which has been fixed using the workaround).
![image](https://user-images.githubusercontent.com/62880272/140529998-9dc7f722-adfc-48d5-a9f6-42ee98d5f6f1.png)

**Comment by Xunnamius** [comment]
@zabakala @TanDung2512 @ngquhuanbl I know it's been a while, but do any of you still have the code/repo that was producing this behavior, or would be willing to create a simple [MRE](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by Xunnamius** [comment]
Closing this for now, but if anyone encounters this issue going forward and https://github.com/babel-utils/babel-plugin-tester/issues/51#issuecomment-540717197 doesn't help, I'll reopen it.
