### ISSUE TITLE
Async plugin support

### ISSUE THREAD

**Issue by moon-stripe** [babel-utils/babel-plugin-tester#83]
- `babel-plugin-tester` version: `10.0.0`
- `node` version: `v14.7.0`
- `npm` (or `yarn`) version: `1.22.10`

Relevant code or config

```javascript
```

What you did:
Write an asynchronous babel plugin.

What happened:
`You appear to be using an async plugin/preset, but Babel has been called synchronously`

Reproduction repository:

Problem description:
`babel-plugin-tester` doesn't support asynchronous plugins (introduced in [7.13.0](https://github.com/babel/babel/blob/main/CHANGELOG.md#v7130-2021-02-22)) because it calls `babel.transform` synchronously [here](https://github.com/babel-utils/babel-plugin-tester/blob/master/src/plugin-tester.js#L155), and `babel.transformSync` [here](https://github.com/babel-utils/babel-plugin-tester/blob/master/src/plugin-tester.js#L340).

Suggested solution:
Check for the existence of `babel.transformAsync` and use that, or fallback to synchronous call to `babel.trasnform`. Happy to make a PR if this is an acceptable solution!

**Comment by kentcdodds** [comment]
Sounds good to me @moon-stripe :)
