### ISSUE TITLE
Including typescript in tests

### ISSUE THREAD

**Issue by davidfloegel** [babel-utils/babel-plugin-tester#86]
Hi,

this is more a question than a bug report - I'm pretty sure I'm missing something fairly obvious.

I'm trying to write a babel plugin that analyses typescript files, so I was trying to write a simple test file that analyses some code and prints out the typescript definition.

```
import pluginTester from "babel-plugin-tester";

pluginTester({
  plugin: identifierReversePlugin,
  snapshot: true,
  tests: [
    {
      code: `
import React from 'react'

interface Test {
  name: string;
}

const User: React.FC<Test> = () => {
  return null;
}
`,
      snapshot: true,
    },
  ],
});

function identifierReversePlugin() {
  return {
    name: "analyse ts",
    visitor: {
      Identifier(idPath) {
        console.log(idPath);
      },
    },
  };
}
```

However, when I run the test it throws the error

```
SyntaxError: unknown: Unexpected reserved word 'interface'. (3:0)

      1 | import React from 'react'
      2 |
    > 3 | interface Test {
        | ^
      4 |   name: string;
      5 | }
      6 |
```

I've tried to google my way through it but whatever I try, the error persists.

Would love some pointers on getting this to run :)

Best

**Comment by Xunnamius** [comment]
I know I'm several months late here, but just for posterity's sake: you probably need to include [@babel/preset-typescript](https://babeljs.io/docs/en/babel-preset-typescript) in your project's .babelrc or in babel-plugin-tester's [`babelOptions`](https://github.com/babel-utils/babel-plugin-tester#options) or, if your plugin is already working outside of your tests, you need to ensure babel-plugin-tester is using your project's babel configuration by setting `babelOptions` and/or [`babelOptions.babelrc`](https://babeljs.io/docs/en/options#babelrc)/[`babelOptions.configFile`](https://babeljs.io/docs/en/options#configfile) appropriately.

**Comment by Xunnamius** [comment]
I'm closing this for now, but feel free to comment with further questions!
