### ISSUE TITLE
Seven PRs with various bugfixes and requested features

### ISSUE THREAD

**Issue by Xunnamius** [babel-utils/babel-plugin-tester#95]
Hello!

First, thanks so much for this awesome package, it has saved me hours of dev time! I've been using it to develop a dozen little babel plugins that do various things for my projects, but I've run into some difficulties using it. My strategy has been to copy-paste some on-the-fly fixes between projects which is not ideal, so I went ahead and bundled these fixes/features together into my own [babel-plugin-tester fork](https://github.com/Xunnamius/babel-plugin-tester#readme) which my team and I have been using successfully for a little while.

Today, I feel confident enough to contribute these fixes back upstream and hopefully retire the fork. They are:

1. [#88: fix plugin order application for fixtures](https://github.com/babel-utils/babel-plugin-tester/pull/88)
    - Fixes #74
2. [#89: fix fixtureOutputExt being ignored in root options.json](https://github.com/babel-utils/babel-plugin-tester/pull/89)
3. [#90: add support for `only`, `skip`, and `title` test options in fixtures](https://github.com/babel-utils/babel-plugin-tester/pull/90)
4. [#91: add support for arbitrary run order of plugin under test](https://github.com/babel-utils/babel-plugin-tester/pull/91)
    - Implements #76
5. [#92: bring back (lightweight) plugin name inference](https://github.com/babel-utils/babel-plugin-tester/pull/92)
    - _Partially_ reverts #78
6. [#93: fix README typos, update with latest features, verbiage improvements](https://github.com/babel-utils/babel-plugin-tester/pull/93)

Additional details are in each PR. With the exception of #91 (which relies on #88), each PR is self-contained and doesn't rely on merging the others, so they can be modified, rejected, or accepted as desired. I also [submitted a PR that combines these other six PRs together](https://github.com/babel-utils/babel-plugin-tester/pull/94) since the octopus merge strategy can't do it effectively.

Thanks again for this package!

**Comment by kentcdodds** [comment]
Wow! This is amazing! How would you like commit access? I don't use this package anymore since I don't write or maintain babel plugins these days. Would you like to take over maintenance?

**Comment by Xunnamius** [comment]
@kentcdodds I'd love to! Babel, its plugins, and I are going to be friends for a long time to come, so it is in my interest to ensure babel-plugin-tester continues to be awesome 😄

**Comment by kentcdodds** [comment]
Alright. I've given you access to the repo as well as access to publish the package on npm.

The tooling in this repo is a bit dated. Auto-publish used to work on travis, but now CI no longer runs at all. I'd change it to GitHub actions if I were you, but it's completely up to you. Do with it as you see fit. Thanks!

**Comment by Xunnamius** [comment]
Aye aye. I'm using a unified Actions-based CI/CD workflow and toolchain across most of my published projects, so I'll be bringing that DX in here eventually. In the meantime, I'll address open issues (might close one or two as out of scope) and resolve pending PRs. Otherwise, I expect to keep most things the same. Thanks again for your work, it's an honor to help maintain this project.
